name: On Call Tutti Action
description: >
  On Call Tutti Action
author: on-call-tutti
runs:
  using: node16
  main: invoke-binary.js

inputs:
  lease-duration:
    description: 'Lease duration'
    required: true
    default: '1'
  role:
    description: 'Role'
    required: true
    default: 'admin'
  path:
    description: 'Folder to find the outputs with pattern'
    required: true
    default: 'admin${{ github.workspace }}/monorepo/projects/algorithms/on-call/comparator/src/main/resources/output/???_ALG???.csv'
outputs:
  result:
    description: 'A table with the results'

branding:
  icon: umbrella
  color: gray-dark
